# PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  pool: 5

development:
  <<: *default
  database: systan_development
  username: <%= ENV['SYSTAN_DATABASE_USERNAME'] %>
  password: <%= ENV['SYSTAN_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: systan_test
  username: <%= ENV['SYSTAN_DATABASE_USERNAME'] %>
  password: <%= ENV['SYSTAN_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['SYSTAN_DATABASE'] %>
  username: <%= ENV['SYSTAN_DATABASE_USERNAME'] %>
  password: <%= ENV['SYSTAN_DATABASE_PASSWORD'] %>
