# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f26aff2e1e0ea61036a707e61e9aa73c80dd06ba7a2121dbe46deb5156d1349530c3b5320860f1be22c85c880727ddd14d05736bc66e3515bbd25ce8ac976eb

test:
  secret_key_base: 3aa3821094992be767b6b894a6cf8fad6314fca5e2e8a304eb8e7e22334cfee1e299e2db08a3ef67665bab51692da2962071b90b43da23546406e88d88feb766

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
